# Numpy Built-in Function

In [1]:
import numpy as np

## Array Creation

In [2]:
# Create an array from llist

arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
# create an array with evenly spaced value

b = np.arange(0,10,2)
print(b)

c = np.arange(-1,-20,-3)
print(c)

[0 2 4 6 8]
[ -1  -4  -7 -10 -13 -16 -19]


In [6]:
# Create an array filled with zero

d = np.zeros((2,3))   # here 2 * 3 is shape 
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Create an array filled with oneabs 

e = np.ones((3,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# Create an identity matrix 
f = np.eye(5)  # 5*5 matrix 
print(f)
print("================")

g = np.eye(3,4)
print(g)

print("================")
h = np.eye(3,4,k=1)   # diagonnal shifet one above 
print(h)
print("================")
i = np.eye(3,4,k=-1)    #  diagonal shifted one belowe
print(i)
print("================")

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## 2. Array Manipulation Function

In [22]:
# Reshape an array 

a1= np.array([1,2,3,4])
print(a1)

print(a1.shape)

print()

a1 = a1.reshape(2,2)
print(a1)

print(a1.shape)

[1 2 3 4]
(4,)

[[1 2]
 [3 4]]
(2, 2)


In [31]:
# flatten an array

a = np.array([[1,2],[3,4]])
print(a)
print()
a_ravel  = np.ravel(a)
print(a_ravel)
print(a_ravel.shape)
print()
a_flatten = a.flatten()
print(a_flatten)
print(a_flatten.shape)

print("======================")

a[0,0] = 32

print(a)
print("======================")
print(a_ravel)
print("======================")
print(a_flatten)

[[1 2]
 [3 4]]

[1 2 3 4]
(4,)

[1 2 3 4]
(4,)
[[32  2]
 [ 3  4]]
[32  2  3  4]
[1 2 3 4]


In [34]:
# Transpose of matrix
t1 = np.array([[1,2],[3,4]])
print(t1)
print('=============================')
print(t1.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [36]:
# Stack arrays verticallya
a = np.array([1,2,3])
b = np.array([4,5,6])

v_stacked = np.vstack((a,b))
print(v_stacked)

[[1 2 3]
 [4 5 6]]


In [37]:
# stack array horizontally

a = np.array([1,2,3])
b = np.array([4,5,6])

h_stacked = np.hstack((a,b))
print(h_stacked)

[1 2 3 4 5 6]


In [38]:
# stack array with hlp of axis 
a = np.array([1,2,3])
b = np.array([4,5,6])

h_stacked = np.stack((a,b),axis=1)
v_stacked = np.stack((a,b),axis=0)
print(h_stacked)
print(v_stacked)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


# 3. Mathematical Functions

In [43]:
# Add two array 

g = np.array([1,2,3])
g1 = g+2
g2 = np.add(g,3)
print(g1)
print(g2)

[3 4 5]
[4 5 6]


In [49]:
# squared elementa

a = np.array([1,2,3])
a1= a**2
print(a1)
a2 = np.square(a)
print(a2)

[1 4 9]
[1 4 9]


In [52]:
# square root of each element 

a4 = np.sqrt(a2)
print(a4)

[1. 2. 3.]


In [54]:
print(a)
print(a1)

[1 2 3]
[1 4 9]


In [53]:
# dot product
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 36


# $ Statistical Funxtion 

In [55]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [56]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [57]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [58]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


# # 6. Random Sampling Functions

In [59]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.50068923 0.32674564 0.53473312]


In [60]:
# Generate random values between 0 and 1
random_vals = np.random.randint(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: 1


In [61]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [5]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# 7. Boolean & Logical Fucntion 

In [6]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [7]:
logical_test = np.array([True, True, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: True


In [3]:
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [4]:
# Any : check if any of the element are ture

logical_test = np.array([False,True,False])
any_true = np.any(logical_test)
print("Any elements True:", any_true)

Any elements True: True


# 8. Set Operator

In [8]:
#Intersection of two arrays
set_a = np.array([1,2,3,4])
set_b= np.array([3,4,5,6])

intersection = np.intersect1d(set_a,set_b)
print(intersection)

[3 4]


In [10]:
# Union of two array 

union = np.union1d(set_a,set_b)
print(union)

[1 2 3 4 5 6]


# 9. Array Attribute an function 

In [12]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array
itemsize = a.itemsize
print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)
print("Itemsize type of a:", itemsize)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64
Itemsize type of a: 8


# Other FUnction 

In [16]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [17]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [18]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
