# Numpy
 - It is a open source python library which is used for fast  numerical calculation.
 - It support multi-dimensional array and matrix,homogeneous data allow
 - It is mostly used in ML,Data Analysis and Ai
 - package and librray which hanldes ndarray

## How to import numpy

In [1]:
import numpy as np # np as alises

## Why Numpy ?
  - Python lists are slow for numerical calculations.
  - NumPy gives ndarray, which stores data in contiguous memory → faster access.
  - Operations are vectorized and written in C → no slow Python loops.
  - Uses less memory compared to Python lists.
  - Supports fast matrix and linear algebra operations.
  - Core dependency for Pandas, Scikit-Learn, TensorFlow, PyTorch, etc.
  - Foundation of data science and machine learning in Python

## Topic 01 :- Array Creation & Shapes

In [2]:
import numpy as np

###  Converting Python Sequences to numpy arrays
  - NumPy arrays can be defined using Python sequences such as lists and tuples
  - a list of numbers will create a 1D array,
  - a list of lists will create a 2D array,
  - further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.

In [10]:
a = np.array([1,2,3,4])   # list -> 1D array
print(a,type(a),a.dtype)

l1 = [2,3,4,5]
a2 = np.array(l1)    # converting list to numpy array 
print(a2,type(a2),a2.dtype)

t =(3,4,5)
a3 = np.array(t)       # converting tuple to numpy array 
print(a3,type(a3),a3.dtype)


[1 2 3 4] <class 'numpy.ndarray'> int64
[2 3 4 5] <class 'numpy.ndarray'> int64
[3 4 5] <class 'numpy.ndarray'> int64


In [ ]:
### How to create a 1D,2D & 3D array ?

In [13]:
a = np.array([1,2,3,4])    # 1D array
b = np.array([[1,2,3],[4,5,6]])   # 2D array
c = np.array([[1,2,3],[4,5,6],[7,8,9]])   # 3D array
print(a)
print("===========================")
print(b)
print("===========================")
print(c)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Important Attributes of array

In [27]:
a = np.array([[1,2,3],[4,5,6]])


a.ndim     # retrun the number of dimenion It is the function which determines the dimensions of the input array
a.shape    # retrun the rows , column 2*3
a.size     # retrun the totral element inside array 
a.dtype    #  # data type (e.g., int64)
a.itemsize #  bytes per element
a.nbytes   # total memory in bytes   8* no.of.element

48

## Type conversion of array

In [33]:
arr = np.array([1.,2.1,3.4])
print(arr,arr.dtype)

arr_int = arr.astype(int)
print(arr_int,arr_int.dtype)

[1.  2.1 3.4] float64
[1 2 3] int64


## Practice Queation


### Q1) Create 1D array from 10 to 50 (inclusive).

In [35]:
a = np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


### Q2) Create 2D array of shape(3,4) filled with numbers 1 to 12

In [38]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:

arr = np.resize(np.arange(1,13),(3,4))
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Q3) Create an array of 6 float values and convert it to int.

In [41]:
arr = np.array([1.1,2.2,3.3,4.4,5.5,6.6])
print(arr)
arr_int = arr.astype(int)
print(arr_int)

[1.1 2.2 3.3 4.4 5.5 6.6]
[1 2 3 4 5 6]


### Create a 3D array with shape (2,3,4) and print:

 - ndim
 - shape
 - size
 - dtype
 - nbytes

In [45]:
arr = np.arange(1,25).reshape(2,3,4)
print(arr)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr.shape)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3
24
int64
8
192
(2, 3, 4)


### Q4) Create an array [1,2,3] with dtype float32, then convert it to int16. Print the change in memory size.

In [51]:
arr = np.array([1, 2, 3], dtype=np.float32)
arr_int = arr.astype(np.int16)

print(arr,arr.nbytes)
print(arr_int,arr_int.nbytes)

[1. 2. 3.] 12
[1 2 3] 6



### Why does this produce only one element? np.array([1, 2, 3, 4], ndmin=2).shape Explain using the concept of dimensions, not guesswork.

In [62]:
np.array([1, 2, 3, 4], ndmin=2).shape # 1*4 = 4 element forcving to coinvberty it into 2d 
np.array([1, 2, 3, 4], ndmin=3).shape

(1, 1, 4)

## Topic 2 — Shape Manipulation

In [63]:
import numpy as np

### 1. shape — see current dimensions

In [65]:
a = np.array([[1,2,3],[4,5,6]])
a.shape    #Shape means: 2 rows, 3 columns.

(2, 3)

### 2. reshape — change shape without changing data
 - ❌ reshape will fail if total elements don’t match.

In [74]:
b = np.arange(12)
print(b.reshape(3,4))
print("==============================")
print(b.reshape(4,3))
print("==============================")
print(b.reshape(2,6))
print("==============================")
print(b.reshape(6,2))
print("==============================")
print(b.reshape(12))
print("==============================")
print(b.reshape(12,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


## 3. ravel vs flatten 
- Both convert to 1D, but not the same:
- If you modify flatten, original stays safe.
- If you modify ravel, you might accidentally change original → Bug city.

In [4]:
x = np.array([[1, 2], [3, 4]])

print(x.ravel() )    # returns VIEW (no new memory)
print(x.flatten())   # returns COPY (new memory)


[1 2 3 4]
[1 2 3 4]


In [5]:
x = np.array([[1, 2], [3, 4]])

a = x.ravel()        # VIEW
b = x.flatten()      # COPY

a[0] = 100           # change the first element of ravel view
b[2] =90
print("x:\n", x)
print("a (ravel):", a)
print("b (flatten):", b)

x:
 [[100   2]
 [  3   4]]
a (ravel): [100   2   3   4]
b (flatten): [ 1  2 90  4]


### Transpose
 - swap axes

In [78]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
m.T   # (2 * 3) become (3 * 2)

array([[1, 4],
       [2, 5],
       [3, 6]])

## expand_dims(arr,axis= 0 or 1 )   0 before the existingf dimenison and 1 after the existing dimension 

In [81]:
arr = np.array([1,2,3])
print(arr)
print(arr.shape)

[1 2 3]
(3,)


In [85]:
np.expand_dims(arr,axis=0).shape

(1, 3)

In [86]:
np.expand_dims(arr,axis=1).shape

(3, 1)

## squeeze

Remove dimensions with size 1:

In [9]:
y = np.array([[[1, 2, 3]]])   # shape (1,1,3)
z = np.squeeze(y)                 # shape (3,)
print(z.shape)
a = np.array([[1,2,3], [4,5,6]])   # shape (2, 3)
b = np.squeeze(a)
print(b.shape)

(3,)
(2, 3)


## PRACTICE Question

### Q1) Convert a (4,3) array to:

(6,2)

(2,6)

(12,)

In [14]:
a = np.arange(12)
print(a)
print("------------------------")
print(a.reshape(6,2))
print("------------------------")
print(a.reshape(2,6))
print("------------------------")
print(a.reshape(12,))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
------------------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Q2) Convert the 1D array np.arange(20) to shape (4,5), then transpose it.

In [15]:
a = np.arange(20)
a = a.reshape(4,5)
print(a)
a.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### Q3) Create array np.arange(1, 25) and reshape into (2, 3, 4).
- Then squeeze it to remove any size-1 dimension.
- Print shapes before and after. 

In [23]:
a = np.arange(1,25)
print(a.shape)

c = a.reshape(2,3,4)
print(c.shape)

b = np.squeeze(a)
print(b.shape)


(24,)
(2, 3, 4)
(24,)


### q4) Convert a (3, 4) matrix into:

- a column vector (shape = (12, 1))

- a row vector (shape = (1, 12))

In [26]:
a = np.arange(12).reshape(3,4)

print(a)

print(a.reshape(12,1))
print(a.reshape(1,12))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


## Vanswer Why does this cause memory sharing? a = np.arange(12).reshape(3,4) b = a.ravel() b[0] = 999 print(a) Answer with the exact technical reason, not some guess. Why does this NOT affect original? c = a.flatten() c[0] = 555 print(a)

# Topic 03 :- Indexing and slicing 

In [28]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [30]:
a[0]    # 0 index row 

array([10, 20, 30])

In [31]:
a[1,2] # 1 index row and 2 index clumn 

np.int64(60)

In [34]:
a[:,1]   # all rows, col 1 → [20 50 80]

array([20, 50, 80])

In [36]:
a[1:,:2] # rows 1→end, cols 0 & 1 → [[40 50], [70 80]]

array([[40, 50],
       [70, 80]])

## BOOLEAN INDEXING

In [40]:
arr = np.array([5,12,25,30,8,50])

arr[arr > 20]

array([25, 30, 50])

In [41]:
arr[(arr> 10) & (arr <40)]

array([12, 25, 30])

In [42]:
arr[arr %2==0]

array([12, 30,  8, 50])

## FANCY INDEXING (index using another array)

In [43]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [45]:
idx =[1,2,3]
arr[idx]

array([20, 30, 40])

In [47]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
m[[0,2],[1,2]]   # what irt will o that c a row 1 colum then 2 row 2 colu,m 

array([2, 9])

In [48]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### MIXING INDEXING TYPES

In [51]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
m[m[:,1]>4,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [60]:

m[m[:,1]<=2,:]

array([[1, 2, 3]])

## 🚨 PRACTICE

## Q) From array

x = np.array([[1,2,3],[4,5,6],[7,8,9]])


print:

row 0

column 2

middle element (5)

last row first 2 columns → [[7,8]]

Get values between 30 and 70 from:

In [62]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
x[0]

array([1, 2, 3])

In [64]:
x[:,2]

array([3, 6, 9])

In [65]:
x[1,1]

np.int64(5)

In [67]:
x[-1,0:2]

array([7, 8])

## Q) Get values between 30 and 70 from:

In [68]:
arr = np.array([10,20,30,40,50,60,70,80])
arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [69]:
arr[2:-2]

array([30, 40, 50, 60])

## Q) From matrix:

m = np.array([[11,22,33,44],
              [55,66,77,88],
              [99,111,122,133]])


Select all rows where the 3rd column is > 70.

In [71]:
m = np.array([[11,22,33,44],
              [55,66,77,88],
              [99,111,122,133]])

m

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 111, 122, 133]])

In [72]:
m[m[:,3]>70,:]

array([[ 55,  66,  77,  88],
       [ 99, 111, 122, 133]])

## Q4) Select elements at positions (0,3), (1,1), (2,0) using fancy indexing.

In [74]:
m = np.array([[11,22,33,44],
              [55,66,77,88],
              [99,111,122,133]])

m

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 111, 122, 133]])

In [76]:
rows=[0,1,2]
col =[3,1,0]
m[rows,col]

array([44, 66, 99])

### Q5) Show an example where slicing changes the original array.
-Because slicing returns a VIEW, not a copy → both variables share the same memory

In [79]:
a = np.arange(10)
b = a[2:6]       # slice (VIEW)
b[0] = 999       # modify b
b[1] = 67
print(a)
print(b)

[  0   1 999  67   4   5   6   7   8   9]
[999  67   4   5]


## Q6) Boolean indexing does NOT change the original
 - Because boolean indexing returns a COPY, not a view.

In [84]:
a = np.arange(10)
b = a[a > 3]      # slice (VIEW)

print(a)
print(b)

print("==================================================")
b[0] = 999       # modify b
b[1] = 67
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[999  67   6   7   8   9]


# BroadCasting
- Broadcasting allows arrays of different shapes to participate in arithmetic without copying data by temporarily stretching dimensions.

If shapes are compatible, NumPy matches trailing dimensions.

## 🔥 Broadcasting Rules (tattoo these in your brain)

Two dimensions are compatible if:

They are equal, OR

One of them is 1

If neither condition is true → broadcasting error.

# Rule of broadcasting

Two arrays can broadcast only if, when comparing dimensions from right to left:

the dimensions are equal, OR

one of them is 1

In [102]:
import numpy as np

In [90]:
a = np.array([1,2,3,4])
print(a.shape)
b=5
a+b

(4,)


array([6, 7, 8, 9])

In [92]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])    # shapw works as (2,3)-> (2,3)
v = np.array([10, 20, 30])    # shape work as (3,) -> (1,3)
print(m.shape)
print(v.shape)
m + v
# [[11 22 33]
#  [14 25 36]]


(2, 3)
(3,)


array([[11, 22, 33],
       [14, 25, 36]])

## 🔥 Column vector broadcasting

In [94]:
m = np.array([[1, 2, 3],
              [4, 5, 6]]) # shape(2,3)
c = np.array([[10],
              [20]])   # hape (2,1)
print(m.shape)
print(c.shape)
m + c

(2, 3)
(2, 1)


array([[11, 12, 13],
       [24, 25, 26]])

## ❌ Broadcasting ERROR example

In [96]:
a = np.ones((3,4))
print(a)
print(a.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [97]:
b = np.ones((2,4))
print(b)
print(b.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(2, 4)


In [98]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

# 3D broadcasting example (very common in ML / images)

In [99]:
img = np.random.rand(256, 256, 3)     # image (H, W, RGB)
bias = np.array([10, 20, 30])         # RGB bias
img + bias


array([[[10.00270109, 20.34015604, 30.34434257],
        [10.12531654, 20.72216972, 30.46353634],
        [10.44012817, 20.92844654, 30.90270901],
        ...,
        [10.48451825, 20.28895717, 30.0190607 ],
        [10.52229083, 20.28548871, 30.01360184],
        [10.47777304, 20.18191597, 30.82897338]],

       [[10.71929049, 20.94102191, 30.11688838],
        [10.38836418, 20.74125803, 30.63447978],
        [10.16432269, 20.50097033, 30.09012764],
        ...,
        [10.92064729, 20.3243311 , 30.12889036],
        [10.07384996, 20.03920727, 30.40137589],
        [10.83310783, 20.7299763 , 30.22784341]],

       [[10.42400755, 20.31132785, 30.13799459],
        [10.76047463, 20.74694705, 30.27649612],
        [10.68693214, 20.19614316, 30.50201435],
        ...,
        [10.35056155, 20.17022513, 30.95549833],
        [10.5796884 , 20.09490576, 30.49147123],
        [10.4909357 , 20.09870845, 30.60023774]],

       ...,

       [[10.83236299, 20.93816918, 30.23649452],
        [10

# 🚀 Broadcasting in place (fastest performance)

In [106]:
a = np.zeros((3,4))
v = np.arange(4)
a += v

print(a)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


# 🚨 PRACTICE

## Q1) Add a 1D array [10,20,30,40] to each row of a (3,4) array of numbers 1–12.

In [111]:
a = np.array([10,20,30,40])
b= np.arange(1,13).reshape(3,4)
print(a)
print(a.shape)
print()
print(b)
print(b.shape)

[10 20 30 40]
(4,)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [109]:
a+b

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52]])

## Q2)Subtract a column vector [[5],[10],[15]] from a (3,4) array of your choice.

In [112]:
a = np.array([[5],[10],[15]])
b = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print()
print(b)
print(b.shape)

[[ 5]
 [10]
 [15]]
(3, 1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [113]:
a-b

array([[5, 4, 3, 2],
       [6, 5, 4, 3],
       [7, 6, 5, 4]])

## Q3) m = np.array([[100,200,300],
              [400,500,600]])
v = np.array([1,2,3])
Multiply them with broadcasting (no loop).

In [114]:
m = np.array([[100,200,300],
              [400,500,600]])
v = np.array([1,2,3])
print(m.shape)
print(v.shape)

(2, 3)
(3,)


In [115]:
m* v

array([[ 100,  400,  900],
       [ 400, 1000, 1800]])

## Q4) Write code that produces a broadcasting error, and fix it without loops by reshaping properly.

In [116]:
import numpy as np

In [117]:
a = np.array([1,2,3,4])
print(a.shape)
b = np.array([[1,3],[4,5]])
print(b.shape)

(4,)
(2, 2)


In [118]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

In [121]:
b=b.reshape(4,1)

In [122]:
a+b

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

## Q5) Predict output shape without running the code, then run and print result:

In [123]:
x = np.ones((2,1,3))
y = np.arange(3)
print((x + y).shape)


(2, 1, 3)


## Q6) Add a 1D array of shape (5,) to a 2D array of shape (5,3) column-wise, using the correct reshape, not a loop.

In [135]:
m = np.array([1,2,3,4,5])
n = np.arange(10,160,10).reshape(5,3)

In [136]:
m.shape

(5,)

In [137]:
n.shape

(5, 3)

In [138]:
m+n

ValueError: operands could not be broadcast together with shapes (5,) (5,3) 

In [141]:
n =n.reshape(3,5)

In [142]:
m+n

array([[ 11,  22,  33,  44,  55],
       [ 61,  72,  83,  94, 105],
       [111, 122, 133, 144, 155]])

# Topic 5 → Vectorization & Ufuncs

## 🔥 What is Vectorization?
  - Vectorization = performing operations on whole arrays at once, without Python loops.

### Why it’s faster:

- NumPy operations are executed in C, not in Python
- No interpreter overhead
- CPU optimized operations

### 🔥 Element-wise arithmetic (vectorized)

In [143]:
 a = np.array([1,2,3,4,5])

print(a+3)
print(a*2)
print(a**2)

[4 5 6 7 8]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


## 🔥 Universal Functions (ufuncs)
- These are fast, C-implemented vectorized functions.

In [149]:
print(np.sqrt(a) )
print()
print(np.log(a))
print()

print(np.sin(a))
print()
print(np.exp(a))
print()
print(np.abs(a))
print()
print(np.round(a))
print()
print(np.power(a, 3))


[1.         1.41421356 1.73205081 2.         2.23606798]

[0.         0.69314718 1.09861229 1.38629436 1.60943791]

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

[1 2 3 4 5]

[1 2 3 4 5]

[  1   8  27  64 125]


## 🔥 Pairwise vectorized operations (extremely useful)

In [150]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
a*b

array([ 10,  40,  90, 160])

## 🔥 Vectorized comparison (boolean mask)

In [153]:
arr = np.array([5, 10, 15, 20])
print(arr > 12 )     # [False False  True  True]
print(arr % 2 == 0)
print((arr >= 10) & (arr <= 20))

[False False  True  True]
[False  True False  True]
[False  True  True  True]


## 🚨 PRACTICE

### Given a = np.array([10, 20, 30, 40]), compute:

double

square

cube

natural log (handle invalid values)

In [155]:
a= np.array([10, 20, 30, 40])
print(a*2)
print(a**2)
print(a**3)
print(np.where(a > 0, np.log(a), np.nan))

[20 40 60 80]
[ 100  400  900 1600]
[ 1000  8000 27000 64000]
[2.30258509 2.99573227 3.40119738 3.68887945]


### For b = np.array([-2, -1, 0, 1, 2]), compute:

absolute value

exponential

sine

In [157]:
b = np.array([-2, -1, 0, 1, 2])

print(np.absolute(b))
print(np.exp(b))
print(np.sin(b))

[2 1 0 1 2]
[0.13533528 0.36787944 1.         2.71828183 7.3890561 ]
[-0.90929743 -0.84147098  0.          0.84147098  0.90929743]


### Q3) Without loops, convert Celsius array:

temp = np.array([0, 20, 37, 100])

In [159]:
temp = np.array([0, 20, 37, 100])
temp =temp*9/5+32
temp

array([ 32. ,  68. ,  98.6, 212. ])

## Q4) Given two arrays:

x = np.array([1,2,3])
y = np.array([4,5,6])


compute vectorized Euclidean distance for each pair:

In [162]:
x = np.array([1,2,3]) 
y = np.array([4,5,6])
dist = np.sqrt(x**2 + y**2)
print(dist)

[4.12310563 5.38516481 6.70820393]


# Topic 6 — Aggregations & Reductions.

## �� Aggregation / Reduction Functions
 - They collapse an array into a single value or a smaller dimension.

In [166]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())
print(a.mean())
print(a.std())
print(a.var())
print(a.min())
print(a.max())
print(a.cumsum())
print(a.cumprod())

15
3.0
1.4142135623730951
2.0
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


## 🔥 Aggregations along axes (critical)
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


In [168]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(m.sum(axis=0))
print(m.sum(axis=1))
print(m.mean(axis=0))


[12 15 18]
[ 6 15 24]
[4. 5. 6.]


## 🔥 Combining aggregations

In [170]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(m.min(axis=0)),print(m.max(axis=0))
print(m.cumsum(axis=1))


[1 2 3]
[7 8 9]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


## 🔥 Aggregations with conditions

In [173]:
arr = np.array([10, 25, 30, 45, 50])
print(arr[arr > 30].mean())   # mean of values > 30
print(arr[arr % 2 == 0].sum()  )# sum of even numbers


47.5
90


## 🔥 Multi-stage reductions (real data processing logic)

In [178]:
scores = np.array([[78, 85, 90],
                   [92, 88, 76],
                   [80, 95, 89]])
student_avg = scores.mean(axis=1)
subject_avg = scores.mean(axis=0)

print(student_avg )
print(subject_avg )

[84.33333333 85.33333333 88.        ]
[83.33333333 89.33333333 85.        ]


# 🚨 PRACTICE

## Q1) From array np.array([5, 10, 15, 20, 25]) compute:

sum

mean

max

index of max

In [179]:
a= np.array([5, 10, 15, 20, 25]) 
print(a.sum())
print(a.mean())
print(a.max())
print(a.argmax())

75
15.0
25
4


## Q2) From matrix

m = np.array([[3, 6, 9],
              [2, 4, 6],
              [1, 8, 7]])


compute:

row-wise sum

column-wise mean

index of max in each row

cumulative sum row-wise

In [182]:
m = np.array([[3, 6, 9], [2, 4, 6], [1, 8, 7]])

print(m.sum(axis=0))
print(m.mean(axis=1))

[ 6 18 22]
[6.         4.         5.33333333]


## Q3) Given:

sales = np.array([[1200, 1300, 1100, 1500],
                  [1000, 1150, 1600, 1700],
                  [950,  1250, 1400, 1800]])


compute:

total sales

sales per person

sales per quarter

best quarter (index)

In [183]:
sales = np.array([[1200, 1300, 1100, 1500],
                  [1000, 1150, 1600, 1700],
                  [950,  1250, 1400, 1800]])
sales

array([[1200, 1300, 1100, 1500],
       [1000, 1150, 1600, 1700],
       [ 950, 1250, 1400, 1800]])

In [184]:
print(sales.sum())

15950


In [185]:
print(sales.sum(axis=0))

[3150 3700 4100 5000]


In [187]:
print(sales.sum(axis=1))

[5100 5450 5400]


In [193]:
sale_quater = sales.sum(axis=0)
print(np.argmax(sale_quater))

3


 ## Q)Write one line of NumPy code (no loops) to compute:

mean of all elements greater than 50 from a 2D matrix

In [195]:
print(m[m>50].mean())

70.0


## For the same matrix:

compute % contribution of each element relative to total sum
(Hint: vectorization + broadcasting)print()

In [197]:
print(m/m.sum()*100)

[[ 3.03030303 18.18181818 27.27272727]
 [12.12121212 16.66666667 22.72727273]]


# Topic 7 — Linear Algebra in NumPy.

## 🔥 Why Linear Algebra matters in NumPy

Because NumPy is built for matrix & vector math.
If you can’t do dot products, matrix multiplication, and transposes confidently, you cannot understand ML models.

## 🔥 1. Transpose

In [199]:
a = np.array([[1,2,3],
              [4,5,6]])
a.T      # shape changes (2,3) → (3,2)


array([[1, 4],
       [2, 5],
       [3, 6]])

## 🔥 2. Dot product (vector)

In [200]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.dot(v1, v2)     # 1*4 + 2*5 + 3*6 = 32


np.int64(32)

## 🔥 3. Matrix multiplication

In [201]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

A @ B   # or np.matmul(A, B)


array([[19, 22],
       [43, 50]])